name: Update Docker Hub Description
on:
  workflow_run:
    workflows:
      - Release
    types:
      - completed
jobs:
  dockerHubDescription:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: kibibitopensrc/kb-fanatic-overflow
